#!/usr/bin/with-contenv sh
NET=${XTUN_NET:-'10.222.0.2/24'}

check_ip() {
  IP_REGEX='^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])$'
  printf '%s' "$1" | tr -d '\n' | grep -Eq "$IP_REGEX"
}
check_ip "$TUNNEL_HOST" || TUNNEL_HOST=$(dig -t A -4 $TUNNEL_HOST +short)

if [ -z "$XTUN_PSK" ]; then
  exit 1
fi
cat <<EOF

================================================

xTun NET: $NET
xTun PSK: $XTUN_PSK
xTun server: $TUNNEL_HOST:$TUNNEL_PORT

================================================

EOF

/opt/xtun/xTun -I $NET -k $XTUN_PSK --mtu 1280 -n -V -c $TUNNEL_HOST -p $TUNNEL_PORT
